#!/bin/bash
#SBATCH -J matrix_mpi           # job name
#SBATCH -o matrix_mpi.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 16             # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:10:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=aashray.arora@stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
ibrun tacc_affinity ./mpi_matrix_size_2_10.out            # run the MPI executable named a.out
