#!/bin/bash
#SBATCH -J par-det-cc           # job name
#SBATCH -o par-det-cc.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:90:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=aashray.arora@stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
export CILK_NWORKERS=32
ibrun ./par-deterministic-cc.o < $1 > $2             # run the MPI executable named a.out
