all:
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/as-skitter-in.txt as-skitter-rand-cc-out.txt 
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-amazon-in.txt com-amazon-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-friendster-in.txt com-friendster-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-orkut-in.txt com-orkut-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-CA-in.txt roadNet-CA-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-TX-in.txt roadNet-TX-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/ca-AstroPh-in.txt ca-AstroPh-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-dblp-in.txt com-dblp-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-lj-in.txt com-lj-rand-cc-out.txt
	sbatch rand-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-PA-in.txt roadNet-PA-rand-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/as-skitter-in.txt as-skitter-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-amazon-in.txt com-amazon-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-friendster-in.txt com-friendster-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-orkut-in.txt com-orkut-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-CA-in.txt roadNet-CA-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-TX-in.txt roadNet-TX-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/ca-AstroPh-in.txt ca-AstroPh-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-dblp-in.txt com-dblp-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/com-lj-in.txt com-lj-det-cc-out.txt
	sbatch det-cc-script /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-PA-in.txt roadNet-PA-det-cc-out.txt
clean:
	rm -rf a  core*
