#!/bin/bash

#SBATCH -J parallel_recur__parenthesis_no_base          # job name
#SBATCH -o parallel_recur_parenthesis_no_base.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 09:30:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=aashray.arora@stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
export CILK_NWORKERS=32
ibrun ./new_recur_parenthesis_no_base.o              # run the MPI executable named a.out
